-- SELECT * FROM FILMS;

MERGE INTO GENRE VALUES (1, 'Комедия');
MERGE INTO GENRE VALUES (2, 'Драма');
MERGE INTO GENRE VALUES (3, 'Мультфильм');
MERGE INTO GENRE VALUES (4, 'Триллер');
MERGE INTO GENRE VALUES (5, 'Документальный');
MERGE INTO GENRE VALUES (6, 'Боевик');

MERGE INTO MPA VALUES (1, 'G');
MERGE INTO MPA VALUES (2, 'PG');
MERGE INTO MPA VALUES (3, 'PG-13');
MERGE INTO MPA VALUES (4, 'R');
MERGE INTO MPA VALUES (5, 'NC-17');